# Generated by Django 2.0.1 on 2018-03-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/shirts/'),
        ),
    ]
