# Generated by Django 2.0.1 on 2018-03-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shirts', '0002_shirt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='last_worn',
            field=models.DateField(blank=True, null=True),
        ),
    ]
